// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6G1tABO-hKZQS0FbGikiF9cTSxGvZS_0',
    appId: '1:934875241324:web:5fbbbcedd2c8031751b149',
    messagingSenderId: '934875241324',
    projectId: 'assignment-d57fc',
    authDomain: 'assignment-d57fc.firebaseapp.com',
    storageBucket: 'assignment-d57fc.firebasestorage.app',
    measurementId: 'G-QR08YQPC9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALFzVVkoV4bT_l7E1KZqGiWwb9mSGJTpM',
    appId: '1:934875241324:android:e12b35d2d8544c4d51b149',
    messagingSenderId: '934875241324',
    projectId: 'assignment-d57fc',
    storageBucket: 'assignment-d57fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5yh2SizOZLon5zBL_JdrnVYoq1AG4ba0',
    appId: '1:934875241324:ios:a450e0c1dbf6140c51b149',
    messagingSenderId: '934875241324',
    projectId: 'assignment-d57fc',
    storageBucket: 'assignment-d57fc.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5yh2SizOZLon5zBL_JdrnVYoq1AG4ba0',
    appId: '1:934875241324:ios:a450e0c1dbf6140c51b149',
    messagingSenderId: '934875241324',
    projectId: 'assignment-d57fc',
    storageBucket: 'assignment-d57fc.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6G1tABO-hKZQS0FbGikiF9cTSxGvZS_0',
    appId: '1:934875241324:web:f0adab991739f10c51b149',
    messagingSenderId: '934875241324',
    projectId: 'assignment-d57fc',
    authDomain: 'assignment-d57fc.firebaseapp.com',
    storageBucket: 'assignment-d57fc.firebasestorage.app',
    measurementId: 'G-KNMCX3689C',
  );
}
